name: Feature Request
description: Propose a new feature, improvement, or idea for YTMDL
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a specific problem or limitation?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Any alternative solutions or workarounds you have considered?
