-- Initial PostgreSQL schema: catalogue, jobs and library files.
--
-- Identifiers are 128 bit random hex strings generated by the application
-- (music.NewID). They stay stable and are safe to hand out through the API,
-- which is why they are stored as text rather than as a database generated
-- surrogate key.

CREATE TABLE artists (
    id          text        PRIMARY KEY,
    name        text        NOT NULL,
    sort_key    text        NOT NULL DEFAULT '',
    provider    text        NOT NULL,
    source_id   text        NOT NULL,
    source_url  text        NOT NULL DEFAULT '',
    image_url   text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    UNIQUE (provider, source_id)
);

CREATE INDEX idx_artists_sort_key ON artists (sort_key);

CREATE TABLE releases (
    id            text        PRIMARY KEY,
    artist_id     text        REFERENCES artists (id) ON DELETE SET NULL,
    title         text        NOT NULL,
    artists_json  jsonb       NOT NULL DEFAULT '[]'::jsonb,
    album_artist  text        NOT NULL DEFAULT '',
    release_type  text        NOT NULL DEFAULT 'album',
    year          integer     NOT NULL DEFAULT 0,
    release_date  text        NOT NULL DEFAULT '',
    track_count   integer     NOT NULL DEFAULT 0,
    cover_url     text        NOT NULL DEFAULT '',
    provider      text        NOT NULL,
    source_id     text        NOT NULL,
    source_url    text        NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL,
    UNIQUE (provider, source_id),
    CONSTRAINT releases_release_type_known CHECK (
        release_type IN ('album', 'single', 'ep', 'live', 'compilation', 'remix')
    )
);

CREATE INDEX idx_releases_artist ON releases (artist_id);

-- tracks holds the internal recording. External identifiers never live here;
-- they belong to track_sources so that one recording can be known to several
-- providers at once.
CREATE TABLE tracks (
    id            text        PRIMARY KEY,
    release_id    text        REFERENCES releases (id) ON DELETE SET NULL,
    artist_id     text        REFERENCES artists (id) ON DELETE SET NULL,
    title         text        NOT NULL,
    artists_json  jsonb       NOT NULL DEFAULT '[]'::jsonb,
    album         text        NOT NULL DEFAULT '',
    album_artist  text        NOT NULL DEFAULT '',
    track_number  integer     NOT NULL DEFAULT 0,
    track_total   integer     NOT NULL DEFAULT 0,
    disc_number   integer     NOT NULL DEFAULT 0,
    disc_total    integer     NOT NULL DEFAULT 0,
    duration_ms   integer     NOT NULL DEFAULT 0,
    year          integer     NOT NULL DEFAULT 0,
    isrc          text        NOT NULL DEFAULT '',
    cover_url     text        NOT NULL DEFAULT '',
    identity_key  text        NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

CREATE INDEX idx_tracks_identity_key ON tracks (identity_key);
CREATE INDEX idx_tracks_release ON tracks (release_id);
CREATE INDEX idx_tracks_artist ON tracks (artist_id);

-- An ISRC identifies exactly one recording, and the deduplication resolves a
-- track by its ISRC before anything else. The unique index therefore both
-- serves that lookup and makes a duplicate recording impossible even when two
-- workers store the same track at the same moment.
CREATE UNIQUE INDEX idx_tracks_isrc ON tracks (isrc) WHERE isrc <> '';

CREATE TABLE track_sources (
    id          text        PRIMARY KEY,
    track_id    text        NOT NULL REFERENCES tracks (id) ON DELETE CASCADE,
    provider    text        NOT NULL,
    kind        text        NOT NULL,
    source_id   text        NOT NULL,
    source_url  text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL,
    UNIQUE (track_id, provider, kind, source_id),
    CONSTRAINT track_sources_kind_known CHECK (kind IN ('metadata', 'media'))
);

CREATE INDEX idx_track_sources_lookup ON track_sources (provider, kind, source_id);

CREATE TABLE jobs (
    id                text        PRIMARY KEY,
    type              text        NOT NULL,
    status            text        NOT NULL,
    label             text        NOT NULL DEFAULT '',
    metadata_provider text        NOT NULL DEFAULT '',
    media_provider    text        NOT NULL DEFAULT '',
    target_id         text        NOT NULL DEFAULT '',
    options_json      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    total             integer     NOT NULL DEFAULT 0,
    completed         integer     NOT NULL DEFAULT 0,
    failed            integer     NOT NULL DEFAULT 0,
    skipped           integer     NOT NULL DEFAULT 0,
    error_code        text        NOT NULL DEFAULT '',
    error_message     text        NOT NULL DEFAULT '',
    created_at        timestamptz NOT NULL,
    updated_at        timestamptz NOT NULL,
    started_at        timestamptz,
    finished_at       timestamptz,
    CONSTRAINT jobs_type_known CHECK (type IN ('artist', 'release', 'track')),
    CONSTRAINT jobs_status_known CHECK (status IN (
        'queued', 'resolving_artist', 'resolving_releases', 'resolving_tracks',
        'deduplicating', 'matching', 'downloading', 'tagging', 'finalizing',
        'completed', 'failed', 'cancelled'
    ))
);

CREATE INDEX idx_jobs_status ON jobs (status);
CREATE INDEX idx_jobs_created_at ON jobs (created_at DESC);

CREATE TABLE job_items (
    id             text             PRIMARY KEY,
    job_id         text             NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    position       integer          NOT NULL,
    status         text             NOT NULL,
    track_id       text             REFERENCES tracks (id) ON DELETE SET NULL,
    track_json     jsonb            NOT NULL,
    label          text             NOT NULL DEFAULT '',
    media_provider text             NOT NULL DEFAULT '',
    media_id       text             NOT NULL DEFAULT '',
    media_url      text             NOT NULL DEFAULT '',
    match_score    double precision NOT NULL DEFAULT 0,
    file_id        text,
    attempts       integer          NOT NULL DEFAULT 0,
    error_code     text             NOT NULL DEFAULT '',
    error_message  text             NOT NULL DEFAULT '',
    created_at     timestamptz      NOT NULL,
    updated_at     timestamptz      NOT NULL,
    started_at     timestamptz,
    finished_at    timestamptz,
    UNIQUE (job_id, position),
    CONSTRAINT job_items_status_known CHECK (status IN (
        'pending', 'matching', 'downloading', 'tagging',
        'completed', 'failed', 'skipped', 'cancelled'
    ))
);

CREATE INDEX idx_job_items_job ON job_items (job_id, position);
CREATE INDEX idx_job_items_status ON job_items (status);
-- The dispatcher asks for the unfinished items of one job on every wake up.
CREATE INDEX idx_job_items_job_status ON job_items (job_id, status);

CREATE TABLE files (
    id              text             PRIMARY KEY,
    track_id        text             REFERENCES tracks (id) ON DELETE SET NULL,
    path            text             NOT NULL UNIQUE,
    size_bytes      bigint           NOT NULL DEFAULT 0,
    codec           text             NOT NULL DEFAULT '',
    container       text             NOT NULL DEFAULT '',
    bitrate_kbps    double precision NOT NULL DEFAULT 0,
    sample_rate     integer          NOT NULL DEFAULT 0,
    channels        integer          NOT NULL DEFAULT 0,
    duration_ms     integer          NOT NULL DEFAULT 0,
    source_provider text             NOT NULL DEFAULT '',
    source_id       text             NOT NULL DEFAULT '',
    source_url      text             NOT NULL DEFAULT '',
    created_at      timestamptz      NOT NULL,
    updated_at      timestamptz      NOT NULL
);

CREATE INDEX idx_files_track ON files (track_id);

CREATE TABLE settings (
    key        text        PRIMARY KEY,
    value      text        NOT NULL,
    updated_at timestamptz NOT NULL
);
